
service: serveless-dynamodb-nodejs

frameworkVersion: '2.55.0'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: /message